#!/bin/bash

conda install -c conda-forge jupyterlab
conda install -c conda-forge xeus-cling
conda install -c conda-forge curl

gcc -o simple Curl.c -lcurl
jupyter lab workspaces import binder/workspace.json
